version: '2'
services:
    epetrolstationbackend-app:
        image: epetrolstationbackend
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://epetrolstationbackend-mysql:3306/epetrolstationbackend?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    epetrolstationbackend-mysql:
        extends:
            file: mysql.yml
            service: epetrolstationbackend-mysql
